sudo: required

services:
  - docker

# code chạy trước khi test
before_install:
  - docker build -t mrlinhdeptrai9988/docker-react-01 -f Dockerfile.dev .

script:
  - docker run -e CI=true mrlinhdeptrai9988/docker-react-01 npm run test -- --coverage